@extends('layouts.app')
@section('title','Daftar risiko')
@section('content')
<div class="work-heading"><div><h1>Daftar risiko</h1><p class="muted">Penilaian, pemilik dan semakan risiko mengikut bahagian.</p></div>@can('create',App\Models\Risk::class)<a class="work-button" href="{{ route('risks.create') }}">Daftar risiko</a>@endcan</div>
<div class="notice">Matriks contoh 5×5 untuk rintis. Skor 1–4 rendah, 5–12 sederhana, 13–25 tinggi. Kaedah ini belum disahkan SUK.</div>
<div class="work-summary">@foreach(['total'=>'Jumlah risiko','high'=>'Risiko tinggi','submitted'=>'Menunggu semakan','returned'=>'Dikembalikan'] as $key=>$label)<a href="{{ route('risks.index', $key === 'high' ? ['level'=>'high'] : ($key === 'total' ? [] : ['status'=>$key])) }}"><strong>{{ $counts[$key] }}</strong>{{ $label }}</a>@endforeach</div>
<section class="work-panel"><form method="get" class="work-actions"><div class="work-field"><label for="q">Cari kod, tajuk atau aset/proses</label><input id="q" name="q" value="{{ request('q') }}" maxlength="100"></div><div class="work-field"><label for="status">Status</label><select id="status" name="status"><option value="">Semua status</option>@foreach(['draft'=>'Draf','submitted'=>'Menunggu semakan','returned'=>'Dikembalikan','reviewed'=>'Disemak'] as $key=>$label)<option value="{{ $key }}" @selected(request('status')===$key)>{{ $label }}</option>@endforeach</select></div><div class="work-field"><label for="level">Tahap risiko</label><select id="level" name="level"><option value="">Semua tahap</option>@foreach(['low'=>'Rendah','medium'=>'Sederhana','high'=>'Tinggi'] as $key=>$label)<option value="{{ $key }}" @selected(request('level')===$key)>{{ $label }}</option>@endforeach</select></div><button class="work-button">Tapis</button><a href="{{ route('risks.index') }}">Kosongkan penapis</a></form>
<div class="work-scroll"><table class="work-table"><thead><tr><th scope="col">Risiko / aset atau proses</th><th scope="col">Bahagian / pemilik</th><th scope="col">Penilaian</th><th scope="col">Status</th><th scope="col">Dikemas kini</th></tr></thead><tbody>@forelse($risks as $risk)<tr><td><a href="{{ route('risks.show',$risk) }}">{{ $risk->code() }} · {{ $risk->title }}</a><span class="sub">{{ $risk->asset_process }}</span></td><td>{{ $risk->department->name }}<span class="sub">{{ $risk->owner->name }}</span></td><td><strong>{{ $risk->score }} / 25</strong><span class="sub">{{ $risk->levelLabel() }}</span></td><td><span class="status-label {{ $risk->status }}">{{ $risk->statusLabel() }}</span></td><td>{{ $risk->updated_at->timezone('Asia/Kuala_Lumpur')->format('d/m/Y H:i') }}</td></tr>@empty<tr><td colspan="5"><div class="empty-state">{{ request('q') || request('status') || request('level') ? 'Tiada risiko sepadan. Kosongkan penapis untuk melihat semua rekod.' : 'Belum ada risiko dalam skop anda.' }}</div></td></tr>@endforelse</tbody></table></div>{{ $risks->links() }}</section>
@endsection
