@extends('layouts.app')
@section('title',$risk->code())
@section('content')
<p><a class="work-button secondary" href="{{ route('risks.treatment',$risk) }}">Pelan rawatan &amp; risiko baki</a></p>
<div class="work-heading"><div><a href="{{ route('risks.index') }}">Daftar risiko</a><h1>{{ $risk->code() }} · {{ $risk->title }}</h1><span class="status-label {{ $risk->status }}">{{ $risk->statusLabel() }}</span></div>@can('update',$risk)<a class="work-button" href="{{ route('risks.edit',$risk) }}">Kemaskini penilaian</a>@endcan</div>
<div class="notice">{{ $risk->method['label'] }}. Status “Disemak” merekodkan semakan penilaian, belum merupakan keputusan penerimaan risiko.</div>
<div class="detail-grid"><section class="work-panel"><h2>Butiran risiko</h2><dl class="work-meta">@foreach(['asset_process'=>'Aset / proses','threat'=>'Ancaman','vulnerability'=>'Kelemahan','consequence'=>'Kesan','existing_controls'=>'Kawalan sedia ada','rationale'=>'Alasan penilaian'] as $key=>$label)<dt>{{ $label }}</dt><dd style="white-space:pre-wrap">{{ $risk->$key }}</dd>@endforeach<dt>Bahagian</dt><dd>{{ $risk->department->name }}</dd><dt>Pemilik</dt><dd>{{ $risk->owner->name }}</dd></dl></section><section class="work-panel"><h2>Penilaian semasa</h2><p><strong style="font-size:32px">{{ $risk->score }} / 25</strong> · {{ $risk->levelLabel() }}</p><p>Kebarangkalian {{ $risk->likelihood }} × Impak {{ $risk->impact }}</p><p class="muted">Rendah: 1–{{ $risk->method['low_max'] }}<br>Sederhana: {{ $risk->method['low_max']+1 }}–{{ $risk->method['medium_max'] }}<br>Tinggi: {{ $risk->method['medium_max']+1 }}–25<br>Kaedah: {{ $risk->method['version'] }}</p>
@foreach(['submit'=>'Hantar untuk semakan','review'=>'Sahkan semakan','return'=>'Kembalikan untuk pembetulan','reassess'=>'Mulakan penilaian semula'] as $action=>$label)@can('transition',[$risk,$action])<form method="post" action="{{ route('risks.transition',$risk) }}" style="margin-top:24px">@csrf<input type="hidden" name="action" value="{{ $action }}"><input type="hidden" name="lock_version" value="{{ $risk->lock_version }}">@if($action!=='submit')<div class="work-field"><label for="comment-{{ $action }}">{{ in_array($action,['return','reassess']) ? 'Sebab (wajib)' : 'Ulasan semakan (pilihan)' }}</label><textarea id="comment-{{ $action }}" name="comment" maxlength="5000" @required(in_array($action,['return','reassess']))>{{ old('action')===$action ? old('comment') : '' }}</textarea></div>@endif<button class="work-button {{ $action==='return' ? 'warning' : '' }}">{{ $label }}</button></form>@endcan @endforeach
</section></div>
<section class="work-panel"><h2>Sejarah penilaian dan keputusan</h2><ul class="timeline">@foreach($events as $event)<li><strong>{{ ['risk.created'=>'Draf didaftarkan','risk.updated'=>'Penilaian dikemas kini','risk.submit'=>'Dihantar untuk semakan','risk.review'=>'Penilaian disemak','risk.return'=>'Dikembalikan','risk.reassess'=>'Penilaian semula dimulakan'][$event->action] ?? $event->action }}</strong><small>{{ $event->actor->name }} · {{ $event->created_at->timezone('Asia/Kuala_Lumpur')->format('d/m/Y H:i') }}</small>@if($event->comment)<p>{{ $event->comment }}</p>@endif<details><summary>Butiran penilaian ketika tindakan</summary><dl class="work-meta" style="margin-top:12px">@foreach(['title'=>'Tajuk','asset_process'=>'Aset / proses','threat'=>'Ancaman','vulnerability'=>'Kelemahan','consequence'=>'Kesan','existing_controls'=>'Kawalan','rationale'=>'Alasan','likelihood'=>'Kebarangkalian','impact'=>'Impak','score'=>'Skor','status'=>'Status'] as $key=>$label)<dt>{{ $label }}</dt><dd>{{ $event->after[$key] ?? '—' }}</dd>@endforeach<dt>Kaedah</dt><dd>{{ $event->after['method']['version'] ?? '—' }}</dd></dl></details></li>@endforeach</ul>{{ $events->links() }}</section>
@endsection
