@extends('layouts.app')
@section('title','Pelan rawatan · '.$risk->code())
@section('content')
<div class="work-heading"><div><a href="{{ route('risks.show',$risk) }}">{{ $risk->code() }} · {{ $risk->title }}</a><h1>Pelan rawatan risiko</h1><p class="muted">Kitaran penilaian {{ $risk->assessment_cycle }} · Skor sebelum rawatan: {{ $risk->score }}/25 ({{ $risk->levelLabel() }})</p></div></div>
<div class="notice">{{ $risk->method['label'] }}. Pengesahan tindakan dan penilaian baki tidak menerima risiko secara automatik.</div>
@if($risk->status!=='reviewed')<div class="notice">Selesaikan semakan penilaian risiko dahulu sebelum menambah atau memproses tindakan rawatan.</div>@endif
<div class="work-summary"><div style="padding:16px"><strong>{{ $current->count() }}</strong> Tindakan kitaran ini</div><div style="padding:16px"><strong>{{ $current->where('status','verified')->count() }}</strong> Disahkan</div><div style="padding:16px"><strong>{{ $current->where('status','submitted')->count() }}</strong> Menunggu pengesahan</div><div style="padding:16px"><strong>{{ $current->filter(fn($item)=>$item->overdue())->count() }}</strong> Lewat</div></div>
@if($workflow->canManage(auth()->user(),$risk))
<section class="work-panel"><details @if(old('form_key')==='new') open @endif><summary>Tambah tindakan rawatan</summary><form class="work-form" method="post" action="{{ route('risk-actions.store',$risk) }}" style="margin-top:20px">@csrf<input type="hidden" name="form_key" value="new"><input type="hidden" name="lock_version" value="{{ old('form_key')==='new' ? old('lock_version') : $risk->lock_version }}">@include('risks.action-fields',['item'=>null,'prefix'=>'new','restore'=>old('form_key')==='new'])<button class="work-button">Tambah tindakan</button></form></details></section>
@endif
@forelse($actions as $item)
<section class="work-panel"><div class="work-heading"><div><h2>#{{ $item->id }} · {{ $item->title }}</h2><p class="muted">Kitaran {{ $item->cycle }} · {{ $item->assignee->name }} · Sasaran {{ $item->due_date->format('d/m/Y') }} @if($item->overdue() && $item->cycle===$risk->assessment_cycle)<strong>· Lewat</strong>@endif</p></div><span class="status-label {{ $item->status==='verified' ? 'approved' : $item->status }}">{{ $item->statusLabel() }}</span></div><p style="white-space:pre-wrap">{{ $item->description }}</p>
@if($item->cycle !== (int)$risk->assessment_cycle)<p class="muted">Rekod kitaran terdahulu. Dipaparkan untuk rujukan sejarah.</p>@endif
@if($workflow->canManage(auth()->user(),$risk) && $item->cycle===(int)$risk->assessment_cycle && in_array($item->status,['open','returned']))<details @if(old('form_key')==='edit-'.$item->id) open @endif><summary>Kemaskini tindakan / pelaksana / tarikh</summary><form class="work-form" method="post" action="{{ route('risk-actions.update',$item) }}" style="margin-top:16px">@csrf @method('put')<input type="hidden" name="form_key" value="edit-{{ $item->id }}"><input type="hidden" name="lock_version" value="{{ old('form_key')==='edit-'.$item->id ? old('lock_version') : $risk->lock_version }}">@include('risks.action-fields',['prefix'=>'edit-'.$item->id,'restore'=>old('form_key')==='edit-'.$item->id])<div class="work-field"><label for="reason-{{ $item->id }}">Sebab perubahan</label><textarea id="reason-{{ $item->id }}" name="comment" required maxlength="5000">{{ old('form_key')==='edit-'.$item->id ? old('comment') : '' }}</textarea></div><button class="work-button">Simpan perubahan</button></form></details>@endif
<h3>Bukti pelaksanaan</h3>@forelse($item->evidence as $evidence)<p><a href="{{ route('risk-evidence.download',$evidence) }}">{{ $evidence->original_name }}</a> · {{ $evidence->created_at->timezone('Asia/Kuala_Lumpur')->format('d/m/Y H:i') }}<br>{{ $evidence->summary }}</p>@empty<p class="muted">Belum ada bukti dihantar.</p>@endforelse
@if($workflow->canSubmit(auth()->user(),$item))<form class="work-form" method="post" enctype="multipart/form-data" action="{{ route('risk-actions.submit',$item) }}">@csrf<input type="hidden" name="form_key" value="submit-{{ $item->id }}"><input type="hidden" name="lock_version" value="{{ old('form_key')==='submit-'.$item->id ? old('lock_version') : $risk->lock_version }}"><div class="work-field"><label for="summary-{{ $item->id }}">Ringkasan pelaksanaan</label><textarea id="summary-{{ $item->id }}" name="summary" required maxlength="5000">{{ old('form_key')==='submit-'.$item->id ? old('summary') : '' }}</textarea></div><div class="work-field"><label for="file-{{ $item->id }}">Fail bukti (PDF, maksimum 10 MB)</label><input type="file" id="file-{{ $item->id }}" name="file" required accept="application/pdf"><small>Bukti terdahulu dikekalkan. Pilih semula fail jika borang gagal disimpan.</small></div><button class="work-button">Hantar bukti untuk pengesahan</button></form>@endif
@if($workflow->canReview(auth()->user(),$item) && in_array($item->status,['submitted','verified']))<form class="work-form" method="post" action="{{ route('risk-actions.decide',$item) }}">@csrf<input type="hidden" name="form_key" value="decision-{{ $item->id }}"><input type="hidden" name="lock_version" value="{{ old('form_key')==='decision-'.$item->id ? old('lock_version') : $risk->lock_version }}"><div class="work-field"><label for="comment-{{ $item->id }}">Ulasan keputusan (wajib)</label><textarea id="comment-{{ $item->id }}" name="comment" required maxlength="5000">{{ old('form_key')==='decision-'.$item->id ? old('comment') : '' }}</textarea></div><div class="work-actions">@if($item->status==='submitted')<button class="work-button" name="action" value="verify">Sahkan tindakan</button><button class="work-button warning" name="action" value="return">Kembalikan untuk pembetulan</button>@else<button class="work-button warning" name="action" value="reopen">Buka semula tindakan</button>@endif</div></form>@endif
</section>@empty<section class="work-panel"><p>Belum ada tindakan rawatan. Selepas risiko disemak, pemilik atau penyelaras boleh menetapkan tindakan.</p></section>@endforelse
<section class="work-panel"><h2>Risiko baki</h2><p class="muted">Nilai kebarangkalian dan impak selepas kawalan dilaksanakan. Sejarah penilaian terdahulu dikekalkan.</p>
@foreach($residuals as $residual)<details @if($loop->first) open @endif><summary>{{ $residual->score }}/25 · {{ ['low'=>'Rendah','medium'=>'Sederhana','high'=>'Tinggi'][$residual->level] }} · {{ $residual->created_at->timezone('Asia/Kuala_Lumpur')->format('d/m/Y H:i') }} · {{ $loop->first && $risk->residualIsCurrent() ? 'Terkini' : 'Sejarah / perlu dinilai semula' }}</summary><p>Kitaran {{ $residual->cycle }} · {{ $residual->assessor->name }} · Kebarangkalian {{ $residual->likelihood }} × Impak {{ $residual->impact }}</p><p><strong>Kawalan:</strong> {{ $residual->controls }}</p><p><strong>Alasan:</strong> {{ $residual->rationale }}</p></details>@endforeach
@if($workflow->canManage(auth()->user(),$risk) && auth()->id()===$risk->owner_id && $current->isNotEmpty() && $current->every(fn($item)=>$item->status==='verified'))
<details @if(old('form_key')==='residual') open @endif><summary>Rekod penilaian risiko baki</summary><form class="work-form" method="post" action="{{ route('risks.residual',$risk) }}" style="margin-top:16px">@csrf<input type="hidden" name="form_key" value="residual"><input type="hidden" name="lock_version" value="{{ old('form_key')==='residual' ? old('lock_version') : $risk->lock_version }}">@foreach(['likelihood'=>'Kebarangkalian selepas rawatan','impact'=>'Impak selepas rawatan'] as $key=>$label)<div class="work-field"><label for="residual-{{ $key }}">{{ $label }}</label><select id="residual-{{ $key }}" name="{{ $key }}" required><option value="">Pilih 1 (terendah) hingga 5 (tertinggi)</option>@for($n=1;$n<=5;$n++)<option value="{{ $n }}" @selected(old('form_key')==='residual' && (int)old($key)===$n)>{{ $n }}</option>@endfor</select></div>@endforeach @foreach(['controls'=>'Kawalan selepas rawatan','rationale'=>'Alasan penilaian baki'] as $key=>$label)<div class="work-field"><label for="residual-{{ $key }}">{{ $label }}</label><textarea id="residual-{{ $key }}" name="{{ $key }}" required maxlength="5000">{{ old('form_key')==='residual' ? old($key) : '' }}</textarea></div>@endforeach<button class="work-button">Simpan penilaian baki</button></form></details>
@else<p>Penilaian baki direkodkan oleh pemilik selepas semua tindakan kitaran ini disahkan.</p>@endif</section>
<section class="work-panel"><h2>Sejarah rawatan</h2><ul class="timeline">@forelse($events as $event)<li><strong>{{ ['treatment.created'=>'Tindakan ditambah','treatment.updated'=>'Tindakan dikemas kini','treatment.submitted'=>'Bukti dihantar','treatment.verify'=>'Tindakan disahkan','treatment.return'=>'Tindakan dikembalikan','treatment.reopen'=>'Tindakan dibuka semula','treatment.residual'=>'Risiko baki dinilai'][$event->action] ?? $event->action }}</strong><small>{{ $event->actor->name }} · {{ $event->created_at->timezone('Asia/Kuala_Lumpur')->format('d/m/Y H:i') }} · Kitaran {{ $event->after['cycle'] }}</small>@if(isset($event->after['action']))<p>#{{ $event->after['action']['id'] }} · {{ $event->after['action']['title'] }} · Sasaran {{ substr($event->after['action']['due_date'],0,10) }}</p>@endif @if($event->comment)<p>{{ $event->comment }}</p>@endif</li>@empty<li>Belum ada tindakan direkodkan.</li>@endforelse</ul>{{ $events->links() }}</section>
@endsection
