@extends('layouts.app')
@section('title', 'Laporan & eksport')
@section('content')
<div class="work-heading"><div><h1>Laporan & eksport</h1><p class="muted">Ringkasan rekod semasa · {{ now('Asia/Kuala_Lumpur')->format('d/m/Y H:i') }} waktu Malaysia.</p></div></div>
<section class="work-panel"><form method="get" class="work-actions"><div class="work-field"><label for="department_id">Skop bahagian</label><select id="department_id" name="department_id">@if(auth()->user()->role !== 'officer')<option value="">Semua bahagian dalam akses anda</option>@endif @foreach($departments as $department)<option value="{{ $department->id }}" @selected($departmentId === $department->id)>{{ $department->name }}</option>@endforeach</select></div><button class="work-button">Tapis laporan</button><a href="{{ route('reports.index') }}">Tetapkan semula</a></form><p class="muted">Ringkasan dan fail eksport menggunakan skop bahagian yang dipilih. CSV boleh dibuka dalam Excel; fail dokumen dan bukti kekal dalam sistem.</p><div class="work-actions">@foreach(['documents'=>'Eksport dokumen','risks'=>'Eksport risiko','actions'=>'Eksport rawatan'] as $dataset=>$label)<a class="work-button secondary" href="{{ route('reports.export', ['dataset'=>$dataset, 'department_id'=>$departmentId]) }}">{{ $label }} (CSV)</a>@endforeach</div></section>
<div class="work-summary">@foreach(['documents'=>'Dokumen','risks'=>'Risiko','actions'=>'Tindakan kitaran semasa','overdue'=>'Tindakan belum disahkan yang lewat'] as $key=>$label)<a href="#{{ $key === 'overdue' ? 'overdue' : $key }}"><strong>{{ $totals[$key] }}</strong>{{ $label }}</a>@endforeach</div>
<section id="documents" class="work-panel"><h2>Status dokumen</h2><p class="muted">Setiap dokumen dikira sekali menggunakan versi terkini.</p><dl class="work-meta">@foreach(['draft'=>'Draf','submitted'=>'Menunggu semakan','reviewed'=>'Menunggu kelulusan','returned'=>'Dikembalikan','approved'=>'Diluluskan'] as $key=>$label)<dt>{{ $label }}</dt><dd>{{ $documentCounts[$key] }}</dd>@endforeach</dl></section>
<section id="risks" class="work-panel"><h2>Tahap risiko awal</h2><p class="muted">Penilaian awal terkini menggunakan matriks contoh rintis. Risiko baki dan keputusan penerimaan tidak dicampurkan dalam kiraan ini.</p><dl class="work-meta">@foreach(['low'=>'Rendah','medium'=>'Sederhana','high'=>'Tinggi'] as $key=>$label)<dt>{{ $label }}</dt><dd>{{ $riskCounts[$key] }}</dd>@endforeach</dl></section>
<section id="actions" class="work-panel"><h2>Status tindakan rawatan</h2><p class="muted">Hanya kitaran semasa bagi risiko berstatus Disemak.</p><dl class="work-meta">@foreach(['open'=>'Belum dihantar','submitted'=>'Menunggu pengesahan','returned'=>'Perlu pembetulan','verified'=>'Disahkan'] as $key=>$label)<dt>{{ $label }}</dt><dd>{{ $actionCounts[$key] }}</dd>@endforeach</dl></section>
<section id="overdue" class="work-panel"><h2>Tindakan lewat tarikh sasaran</h2><p class="muted">Tindakan belum disahkan dengan tarikh sebelum hari ini, mengikut waktu Malaysia. Bukti yang sudah dihantar masih boleh menunggu pengesahan.</p><p class="mobile-hint">Leret jadual untuk melihat semua lajur.</p><div class="work-scroll" tabindex="0" role="region" aria-label="Tindakan lewat"><table class="work-table"><thead><tr><th>Tindakan / Risiko</th><th>Bahagian</th><th>Pelaksana</th><th>Sasaran</th><th>Status</th></tr></thead><tbody>@forelse($overdueActions as $action)<tr><td><a href="{{ route('risks.treatment',$action->risk) }}">{{ $action->title }}</a><span class="sub">{{ $action->risk->code() }}</span></td><td>{{ $action->risk->department?->name }}</td><td>{{ $action->assignee?->name }}</td><td>{{ $action->due_date->format('d/m/Y') }}</td><td>{{ $action->statusLabel() }}</td></tr>@empty<tr><td colspan="5" class="empty-state">Tiada tindakan lewat dalam skop pilihan anda.</td></tr>@endforelse</tbody></table></div>{{ $overdueActions->links() }}</section>
@endsection
