@extends('layouts.app')
@section('title',$document->code)
@section('content')
<div class="work-heading"><div><a href="{{ route('documents.index') }}">← Daftar dokumen</a><h1>{{ $document->title }}</h1><p class="muted">{{ $document->code }} · {{ $document->department->name }}</p></div><span class="status-label {{ $latest->status }}">{{ $latest->statusLabel() }}</span></div><div class="detail-grid"><div><section class="work-panel"><h2>Versi semasa · {{ $latest->number }}</h2><dl class="work-meta"><dt>Pemilik</dt><dd>{{ $document->owner->name }}</dd><dt>Fail</dt><dd><a href="{{ route('versions.download',$latest) }}">{{ $latest->original_name }}</a> <small class="muted">({{ number_format($latest->size/1024,1) }} KB)</small></dd><dt>Penyemak</dt><dd>{{ $latest->reviewer?->name ?? 'Belum disemak' }}</dd><dt>Pelulus</dt><dd>{{ $latest->approver?->name ?? 'Belum diluluskan' }}</dd></dl></section>
@can('update',$latest)<section class="work-panel"><h2>Kemas kini draf</h2><form method="post" action="{{ route('versions.update',$latest) }}" enctype="multipart/form-data">@csrf @method('put')<input type="hidden" name="lock_version" value="{{ $latest->lock_version }}"><div class="work-field"><label for="title">Tajuk dokumen</label><input id="title" name="title" value="{{ old('title',$latest->title ?? $document->title) }}" maxlength="255" required></div><div class="work-field"><label for="file">Ganti fail (pilihan)</label><input id="file" name="file" type="file" accept=".pdf,.docx"><small>PDF atau DOCX · Maksimum 10 MB. Biarkan kosong untuk mengekalkan fail semasa.</small></div><button class="work-button secondary">Simpan perubahan</button></form></section>@endcan
@php($available = collect(['submit'=>'Hantar untuk semakan','review'=>'Sahkan semakan','approve'=>'Luluskan versi','return'=>'Kembalikan untuk pembetulan'])->filter(fn($label,$action)=>auth()->user()->can('transition',[$latest,$action])))
@if($available->isNotEmpty())<section class="work-panel"><h2>Keputusan seterusnya</h2><p class="muted">Keputusan dikenakan pada versi {{ $latest->number }} dan direkodkan bersama nama anda.</p><form method="post" action="{{ route('versions.transition',$latest) }}">@csrf<input type="hidden" name="lock_version" value="{{ $latest->lock_version }}"><div class="work-field"><label for="comment">Ulasan</label><textarea id="comment" name="comment" maxlength="2000">{{ old('comment') }}</textarea><small>Wajib diisi jika dokumen dikembalikan.</small></div><div class="work-actions">@foreach($available as $action=>$label)<button class="work-button {{ $action==='return'?'warning':'' }}" name="action" value="{{ $action }}">{{ $label }}</button>@endforeach</div></form></section>@elseif($latest->status !== 'approved')<div class="notice">{{ $latest->status === 'submitted' ? 'Menunggu penyemak yang berasingan daripada pemilik.' : ($latest->status === 'reviewed' ? 'Menunggu pelulus yang berasingan daripada pemilik dan penyemak.' : 'Perubahan draf hanya boleh dibuat oleh pemilik dokumen.') }}</div>@endif
@if($latest->status === 'approved')@can('newVersion',$document)<section class="work-panel"><h2>Sediakan versi baharu</h2><p class="muted">Versi diluluskan kekal dalam sejarah. Fail baharu akan melalui semakan dan kelulusan semula.</p><form method="post" action="{{ route('documents.versions.store',$document) }}" enctype="multipart/form-data">@csrf<div class="work-field"><label for="new-file">Fail versi baharu</label><input id="new-file" name="file" type="file" accept=".pdf,.docx" required><small>PDF atau DOCX · Maksimum 10 MB.</small></div><button class="work-button">Simpan versi baharu sebagai draf</button></form></section>@endcan @endif
<section class="work-panel"><h2>Sejarah versi</h2><div class="work-scroll" tabindex="0" role="region" aria-label="Sejarah versi"><table class="work-table"><thead><tr><th>Versi / Tajuk</th><th>Status</th><th>Fail</th></tr></thead><tbody>@foreach($document->versions as $version)<tr><td>Versi {{ $version->number }}<span class="sub">{{ $version->title ?? $document->title }}</span></td><td><span class="status-label {{ $version->status }}">{{ $version->statusLabel() }}</span></td><td><a href="{{ route('versions.download',$version) }}">Muat turun</a></td></tr>@endforeach</tbody></table></div></section></div>
<aside><section class="work-panel"><h2>Jejak audit</h2><ol class="timeline">@forelse($document->auditEvents as $event)<li><strong>{{ ['document.created'=>'Dokumen didaftarkan','version.created'=>'Versi baharu disediakan','version.updated'=>'Draf dikemas kini','version.submit'=>'Dihantar untuk semakan','version.review'=>'Semakan disahkan','version.approve'=>'Versi diluluskan','version.return'=>'Dikembalikan'][$event->action] ?? $event->action }}</strong><small>{{ $event->actor->name }} · Versi {{ $event->after['number'] ?? '' }}</small><small>{{ $event->created_at->timezone('Asia/Kuala_Lumpur')->format('d/m/Y H:i') }}</small>@if($event->comment)<p>{{ $event->comment }}</p>@endif</li>@empty<li class="muted">Tiada peristiwa direkodkan.</li>@endforelse</ol></section></aside></div>
@endsection
