const { chromium } = require(process.env.ISMS_PLAYWRIGHT_PATH || 'C:/Users/Firdaus/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs = require('fs');
const path = require('path');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '..');
const output = path.join(root, 'docs/review/laravel');
fs.mkdirSync(output, { recursive: true });
const base = process.env.ISMS_URL || 'http://127.0.0.1:8099';

(async () => {
  const browser = await chromium.launch({ headless: true, executablePath: process.env.ISMS_CHROME || 'C:/Program Files/Google/Chrome/Application/chrome.exe' });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    const password = fs.readFileSync(path.join(root, 'application/.env'), 'utf8').match(/^ISMS_DEMO_PASSWORD=(.+)$/m)?.[1].trim();
    assert(password, 'Local demo password is required');
    const checks = [];
    const passed = name => { checks.push(name); console.log('PASS ' + name); };
    const login = async email => {
      await page.goto(base + '/login');
      await page.getByLabel('E-mel', { exact: true }).fill(email + '@example.test');
      await page.getByLabel('Kata laluan', { exact: true }).fill(password);
      await page.getByRole('button', { name: 'Log masuk', exact: true }).click();
      await page.waitForURL(email === 'admin' ? '**/admin/users' : '**/documents');
    };
    const logout = async () => {
      await page.getByRole('button', { name: 'Log keluar', exact: true }).click();
      await page.waitForURL(base + '/');
    };
    const overflow = async () => assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), 'Page must not overflow');
    await page.goto(base);
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: path.join(output, 'landing-desktop.png'), fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await overflow();
    await page.screenshot({ path: path.join(output, 'landing-mobile.png'), fullPage: true });
    passed('Landing desktop/mobile');
    await page.goto(base + '/login');
    await page.waitForLoadState('networkidle');
    await overflow();
    await page.screenshot({ path: path.join(output, 'login-mobile.png'), fullPage: true });
    await page.setViewportSize({ width: 1440, height: 1000 });
    await login('pegawai');
    const csrfDenied = await page.request.post(base + '/documents', { data: { code: 'NO-CSRF', title: 'Must not be saved' } });
    assert.equal(csrfDenied.status(), 419);
    assert.equal((await page.request.get(base + '/.env')).status(), 404);
    assert.equal((await page.request.get(base + '/storage/documents/example.pdf')).status(), 404);
    passed('CSRF and private project/storage paths blocked');
    assert(await page.getByRole('link', { name: 'DEMO-DOC-001', exact: true }).isVisible());
    assert.equal(await page.getByRole('link', { name: 'DEMO-DOC-004', exact: true }).count(), 0);
    await page.screenshot({ path: path.join(output, 'documents-desktop.png'), fullPage: true });
    await page.getByLabel('Cari kod atau tajuk').fill('NO-SUCH-DOCUMENT');
    await page.getByRole('button', { name: 'Tapis', exact: true }).click();
    assert(await page.getByText('Tiada dokumen sepadan.', { exact: false }).isVisible());
    await page.getByRole('link', { name: 'Kosongkan', exact: true }).click();
    passed('Officer scoped register and search/reset');
    await page.getByRole('link', { name: 'Daftar dokumen', exact: true }).last().click();
    const code = 'E2E-' + Date.now();
    const pdf = Buffer.from('%PDF-1.4\n1 0 obj\n<< /Type /Catalog >>\nendobj\ntrailer\n<< /Root 1 0 R >>\n%%EOF');
    await page.getByLabel('Kod dokumen', { exact: true }).fill(code);
    await page.getByLabel('Tajuk dokumen', { exact: true }).fill('Dokumen ujian browser');
    await page.getByLabel('Fail dokumen', { exact: true }).setInputFiles({ name: 'browser.pdf', mimeType: 'application/pdf', buffer: pdf });
    await page.getByRole('button', { name: 'Simpan draf', exact: true }).click();
    await page.waitForURL(/\/documents\/\d+$/);
    const recordUrl = page.url();
    await page.setViewportSize({ width: 390, height: 844 });
    await overflow();
    await page.screenshot({ path: path.join(output, 'draft-mobile.png'), fullPage: true });
    await page.getByRole('button', { name: 'Hantar untuk semakan', exact: true }).click();
    await page.waitForLoadState('networkidle');
    assert(await page.getByText('Menunggu semakan', { exact: true }).first().isVisible());
    passed('Real private upload and mobile submit');
    await logout();
    await login('penyelaras');
    await page.goto(recordUrl);
    await page.getByLabel('Ulasan', { exact: true }).fill('Betulkan tajuk contoh');
    await page.getByRole('button', { name: 'Kembalikan untuk pembetulan', exact: true }).click();
    await page.waitForLoadState('networkidle');
    assert(await page.getByText('Dikembalikan', { exact: true }).first().isVisible());
    await logout();
    await login('pegawai');
    await page.goto(recordUrl);
    await page.getByLabel('Tajuk dokumen', { exact: true }).fill('Dokumen ujian browser dibetulkan');
    await page.getByRole('button', { name: 'Simpan perubahan', exact: true }).click();
    await page.waitForLoadState('networkidle');
    await page.getByRole('button', { name: 'Hantar untuk semakan', exact: true }).click();
    await page.waitForLoadState('networkidle');
    await logout();
    await login('penyelaras');
    await page.goto(recordUrl);
    await page.getByRole('button', { name: 'Sahkan semakan', exact: true }).click();
    await page.waitForLoadState('networkidle');
    passed('Return, correction, resubmit and independent review');
    await logout();
    await login('pelulus');
    await page.goto(recordUrl);
    await page.getByRole('button', { name: 'Luluskan versi', exact: true }).click();
    await page.waitForLoadState('networkidle');
    assert(await page.getByText('Diluluskan', { exact: true }).first().isVisible());
    assert(await page.getByText('Betulkan tajuk contoh', { exact: true }).isVisible());
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.screenshot({ path: path.join(output, 'approved-desktop.png'), fullPage: true });
    const downloadPromise = page.waitForEvent('download');
    await page.getByRole('link', { name: 'Muat turun', exact: true }).first().click();
    const download = await downloadPromise;
    assert.equal(download.suggestedFilename(), 'browser.pdf');
    passed('Independent approval, audit and authenticated download');
    await logout();
    await login('pegawai.kewangan');
    assert.equal((await page.goto(recordUrl)).status(), 403);
    passed('Other department denied through direct URL');
    await logout();
    await login('pegawai');
    await page.goto(recordUrl);
    assert.equal(await page.getByRole('button', { name: 'Simpan perubahan', exact: true }).count(), 0);
    await page.getByLabel('Fail versi baharu').setInputFiles({ name: 'browser-v2.pdf', mimeType: 'application/pdf', buffer: pdf });
    await page.getByRole('button', { name: 'Simpan versi baharu sebagai draf', exact: true }).click();
    await page.waitForLoadState('networkidle');
    assert(await page.getByRole('heading', { name: 'Versi semasa · 2', exact: true }).isVisible());
    assert.equal(await page.getByRole('link', { name: 'Muat turun', exact: true }).count(), 2);
    passed('Approved immutable version retained with new draft');
    await page.setViewportSize({ width: 390, height: 844 });
    await page.goto(base + '/documents');
    await overflow();
    await page.screenshot({ path: path.join(output, 'documents-mobile.png'), fullPage: true });
    await page.goto(base + '/documents/create');
    await overflow();
    await page.screenshot({ path: path.join(output, 'create-mobile.png'), fullPage: true });
    passed('Mobile register and form fit');
    await logout();
    await login('admin');
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.screenshot({ path: path.join(output, 'admin-desktop.png'), fullPage: true });
    await page.getByRole('link', { name: 'Bahagian', exact: true }).click();
    assert(await page.getByRole('heading', { name: 'Bahagian', exact: true }).isVisible());
    const suffix = Date.now();
    const departmentName = 'Bahagian E2E ' + suffix;
    await page.getByLabel('Kod bahagian').fill('E2E-' + suffix);
    await page.getByLabel('Nama bahagian').fill(departmentName);
    await page.getByRole('button', { name: 'Tambah bahagian', exact: true }).click();
    await page.waitForLoadState('networkidle');
    await page.getByRole('link', { name: 'Pengguna', exact: true }).click();
    const newEmail = 'e2e.' + suffix + '@example.test';
    await page.getByLabel('Nama', { exact: true }).fill('Pengguna E2E');
    await page.getByLabel('E-mel', { exact: true }).fill(newEmail);
    await page.getByLabel('Bahagian', { exact: true }).selectOption({ label: departmentName });
    await page.getByLabel('Peranan', { exact: true }).selectOption('officer');
    await page.getByLabel('Kata laluan sementara', { exact: true }).fill(password);
    await page.getByRole('button', { name: 'Tambah akaun', exact: true }).click();
    await page.waitForLoadState('networkidle');
    await page.getByRole('row').filter({ hasText: newEmail }).getByRole('link', { name: 'Urus akaun' }).click();
    await page.getByLabel('Status akaun').selectOption('0');
    await page.getByRole('button', { name: 'Simpan akaun', exact: true }).click();
    await page.waitForLoadState('networkidle');
    assert(await page.getByRole('row').filter({ hasText: newEmail }).getByText('Tidak aktif', { exact: true }).isVisible());
    await logout();
    await page.goto(base + '/login');
    await page.getByLabel('E-mel', { exact: true }).fill(newEmail);
    await page.getByLabel('Kata laluan', { exact: true }).fill(password);
    await page.getByRole('button', { name: 'Log masuk', exact: true }).click();
    await page.waitForLoadState('networkidle');
    assert(await page.getByRole('alert').isVisible());
    passed('Admin creates department/account, deactivates account and inactive login is denied');
    assert.deepEqual(errors, []);
    passed('No browser JavaScript errors');
    fs.writeFileSync(path.join(output, 'checks.json'), JSON.stringify({ base, checks, errors, note: 'Synthetic E2E record retained in development DB; no real data.' }, null, 2));
  } catch (error) {
    const lastPage = browser.contexts().flatMap(context => context.pages()).at(-1);
    if (lastPage) {
      console.log('Failure page: ' + lastPage.url());
      console.log(await lastPage.locator('h1, label').allTextContents());
      await lastPage.screenshot({ path: path.join(output, 'failure.png'), fullPage: true });
    }
    throw error;
  } finally { await browser.close(); }
})().catch(error => { console.error(error.message); process.exitCode = 1; });
