const { chromium } = require('C:/Users/Firdaus/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const output = path.resolve(__dirname, '../docs/review');
fs.mkdirSync(output, { recursive: true });
(async () => {
  const browser = await chromium.launch({headless:true, executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
  const page = await browser.newPage({viewport:{width:1440,height:1050},deviceScaleFactor:1});
  const errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  const checks=[];
  const pass = label => { checks.push(label); console.log('PASS '+label); };
  const rows = count => page.waitForFunction(n=>document.querySelectorAll('tbody tr').length===n,count);
  try {
    await page.goto('http://127.0.0.1:8098/',{waitUntil:'networkidle'});
    await page.getByRole('heading',{name:'Gambaran keseluruhan',exact:true}).waitFor();
    await page.keyboard.press('Tab');
    assert.equal(await page.evaluate(()=>document.activeElement.className),'skip');
    await page.keyboard.press('Enter');
    assert.equal(await page.evaluate(()=>document.activeElement.id),'main');
    await page.getByRole('heading',{name:'Gambaran keseluruhan',exact:true}).waitFor();
    assert.ok(!page.url().endsWith('#main'));
    pass('Keyboard skip link preserves route and focuses content');
    await page.evaluate(()=>{document.activeElement.blur();window.scrollTo(0,0);});
    await page.screenshot({path:path.join(output,'desktop.png'),fullPage:true});
    pass('Desktop overview renders');
    await page.getByRole('button',{name:'Lewat (2)',exact:true}).click();
    assert.equal(await page.locator('.task-row').count(),2);
    pass('Dashboard overdue filter');
    await page.getByRole('button',{name:'Kebarangkalian 4, impak 4: 1 risiko',exact:true}).click();
    await page.waitForURL('**/#risks?cell=4%2C4');
    assert.equal(await page.locator('tbody tr').count(),1);
    await page.getByRole('button',{name:'Akses akaun selepas pertukaran pegawai',exact:true}).click();
    await page.getByRole('dialog').waitFor();
    await page.keyboard.press('Escape');
    assert.equal(await page.getByRole('dialog').count(),0);
    assert.equal(await page.evaluate(()=>document.activeElement.textContent),'Akses akaun selepas pertukaran pegawai');
    pass('Risk matrix drilldown and dialog Escape/focus restoration');
    await page.getByRole('button',{name:'Kosongkan penapis',exact:true}).click();
    await page.waitForURL('**/#risks');
    await page.getByRole('button',{name:'Seterusnya',exact:true}).click();
    await page.waitForURL('**/#risks?p=2');
    await rows(2);
    assert.equal(await page.locator('tbody tr').count(),2);
    await page.goBack();
    await page.waitForURL('**/#risks');
    await rows(6);
    assert.equal(await page.locator('tbody tr').count(),6);
    pass('Bounded pagination and browser back');
    await page.getByRole('searchbox').fill('xyz-tiada');
    await page.getByRole('button',{name:'Cari',exact:true}).click();
    await page.getByRole('heading',{name:'Tiada rekod sepadan',exact:true}).waitFor();
    await page.locator('.toolbar [data-action="reset-filter"]').click();
    await page.waitForURL('**/#risks');
    await page.getByRole('combobox').selectOption('Tinggi');
    await page.waitForURL('**/#risks?filter=Tinggi');
    await rows(2);
    assert.equal(await page.locator('tbody tr').count(),2);
    await page.getByRole('combobox').focus();
    await page.keyboard.press('ArrowDown');
    await page.keyboard.press('Enter');
    pass('Search no-results, clear and native filter selection');
    await page.getByRole('button',{name:'Daftar risiko',exact:true}).click();
    await page.getByRole('button',{name:'Simpan risiko contoh',exact:true}).click();
    assert.equal(await page.locator('[aria-invalid="true"]').count(),5);
    assert.equal(await page.evaluate(()=>document.activeElement.id),'title');
    await page.getByLabel('Tajuk risiko').fill('Risiko ujian <script>');
    await page.getByLabel('Aset / proses').fill('Aset rekaan');
    await page.getByLabel('Pemilik risiko').fill('Pegawai Contoh');
    await page.getByLabel('Bahagian',{exact:false}).fill('Unit Contoh');
    await page.getByLabel('Tarikh semakan').fill('31/02/2026');
    await page.getByRole('button',{name:'Simpan risiko contoh',exact:true}).click();
    assert.equal(await page.locator('#due').getAttribute('aria-invalid'),'true');
    await page.getByLabel('Tarikh semakan').fill('15/10/2026');
    await page.getByLabel('Kebarangkalian contoh').selectOption('5');
    await page.getByLabel('Impak contoh').selectOption('5');
    await page.getByRole('button',{name:'Simpan risiko contoh',exact:true}).click();
    await page.waitForURL('**/#risks');
    await page.getByRole('button',{name:'Risiko ujian <script>',exact:true}).waitFor();
    assert.equal(await page.locator('script:not([src])').count(),0);
    pass('Required fields, date validation and escaped risk creation');
    await page.locator('.nav-link[href="#overview"]').click();
    await page.getByText('3 risiko pada tahap tinggi',{exact:true}).waitFor();
    await page.locator('.nav-link[href="#risks"]').click();
    pass('Dashboard high-risk count recomputed after creation');
    await page.getByRole('button',{name:'Daftar risiko',exact:true}).click();
    await page.getByLabel('Tajuk risiko').fill('Draf disambung');
    await page.getByRole('button',{name:'Batal',exact:true}).click();
    await page.getByRole('button',{name:'Daftar risiko',exact:true}).click();
    assert.equal(await page.getByLabel('Tajuk risiko').inputValue(),'Draf disambung');
    await page.keyboard.press('Escape');
    await page.getByRole('status').filter({hasText:'Draf dikekalkan'}).waitFor();
    pass('In-session draft survives cancel/reopen');
    await page.locator('.nav-link[href="#actions"]').click();
    await page.getByRole('button',{name:'Lengkapkan bukti ujian pemulihan sandaran',exact:true}).click();
    await page.getByRole('button',{name:'Simulasi hantar untuk pengesahan',exact:true}).click();
    await page.locator('.nav-link[href="#overview"]').click();
    await page.getByRole('button',{name:'Lewat (1)',exact:true}).waitFor();
    await page.locator('.nav-link[href="#history"]').click();
    await page.getByText('Tindakan dihantar untuk pengesahan (simulasi)',{exact:true}).waitFor();
    pass('Simulated status propagates to dashboard and audit');
    await page.locator('.nav-link[href="#documents"]').click();
    await page.getByRole('button',{name:'Prosedur kawalan akses',exact:true}).click();
    await page.getByRole('heading',{name:'Pratonton kandungan contoh',exact:true}).waitFor();
    await page.keyboard.press('Escape');
    await page.locator('.nav-link[href="#controls"]').click();
    await page.getByRole('button',{name:'Sandaran maklumat',exact:true}).click();
    await page.getByRole('heading',{name:'Justifikasi',exact:true}).waitFor();
    await page.keyboard.press('Escape');
    pass('Document and SoA details');
    await page.locator('.nav-link[href="#reports"]').click();
    const downloadPromise=page.waitForEvent('download');
    await page.locator('[data-export="risks"]').click();
    const download=await downloadPromise;
    assert.equal(download.suggestedFilename(),'CONTOH-eISMS-risks-2026-10-02.csv');
    await download.saveAs(path.join(output,'sample-export.csv'));
    assert.ok(fs.readFileSync(path.join(output,'sample-export.csv'),'utf8').includes('Risiko ujian <script>'));
    pass('CSV downloads real synthetic data');
    await page.goto('http://127.0.0.1:8098/#does-not-exist');
    await page.getByRole('heading',{name:'Halaman tidak ditemui',exact:true}).waitFor();
    await page.getByRole('link',{name:'Kembali ke papan pemuka',exact:true}).click();
    await page.reload({waitUntil:'networkidle'});
    pass('Unknown route recovery and reset on reload');
    await page.goto('http://127.0.0.1:8098/#risks');
    await page.screenshot({path:path.join(output,'risks-desktop.png'),fullPage:true});
    await page.getByRole('button',{name:'Daftar risiko',exact:true}).click();
    await page.screenshot({path:path.join(output,'form-desktop.png'),fullPage:true});
    await page.keyboard.press('Escape');
    await page.setViewportSize({width:390,height:844});
    await page.goto('http://127.0.0.1:8098/#overview');
    await page.evaluate(()=>{document.activeElement.blur();window.scrollTo(0,0);});
    await page.screenshot({path:path.join(output,'mobile.png'),fullPage:true});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
    for(const route of ['risks','documents','actions','controls','reports','history']){
      await page.locator(`.nav-link[href="#${route}"]`).click();
      assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Overflow '+route);
    }
    await page.locator('.nav-link[href="#risks"]').click();
    await page.getByRole('button',{name:'Daftar risiko',exact:true}).click();
    await page.screenshot({path:path.join(output,'form-mobile.png'),fullPage:true});
    await page.getByRole('button',{name:'Simpan risiko contoh',exact:true}).scrollIntoViewIfNeeded();
    const saveBounds=await page.getByRole('button',{name:'Simpan risiko contoh',exact:true}).boundingBox();
    assert.ok(saveBounds.y>=0 && saveBounds.y+saveBounds.height<=844);
    assert.ok(await page.getByRole('button',{name:'Simpan risiko contoh',exact:true}).isVisible());
    await page.keyboard.press('Escape');
    await page.emulateMedia({reducedMotion:'reduce'});
    assert.equal(await page.locator('.button').first().evaluate(el=>getComputedStyle(el).transitionDuration),'0s');
    pass('All routes fit 390px; mobile form and reduced motion');
    await page.setViewportSize({width:1440,height:1000});
    await page.goto('http://127.0.0.1:8098/landing.html',{waitUntil:'networkidle'});
    await page.screenshot({path:path.join(output,'landing-desktop.png'),fullPage:true});
    for(const [record,title] of [['TND-001','Lengkapkan bukti ujian pemulihan sandaran'],['DOC-002','Prosedur kawalan akses'],['RSK-2026-001','Akses akaun selepas pertukaran pegawai']]){
      await page.locator(`.register-open[href$="record=${record}"]`).click();
      await page.getByRole('dialog').getByRole('heading',{name:title,exact:true}).waitFor();
      await page.keyboard.press('Escape');
      await page.waitForFunction(()=>!location.hash.includes('record='));
      await page.goto('http://127.0.0.1:8098/landing.html');
    }
    pass('Landing record links open exact details and close to owning list');
    assert.equal(await page.locator('.module-row').count(),6);
    await page.getByRole('link',{name:'Modul utama',exact:true}).click();
    await page.getByRole('heading',{name:'Modul pengurusan ISMS',exact:true}).waitFor();
    await page.locator('.module-row[href="index.html#risks"]').click();
    await page.getByRole('heading',{name:'Daftar risiko',exact:true}).waitFor();
    await page.getByRole('link',{name:'Kembali ke portal',exact:true}).click();
    await page.getByRole('link',{name:'Buka demo',exact:true}).click();
    await page.getByRole('heading',{name:'Gambaran keseluruhan',exact:true}).waitFor();
    await page.goto('http://127.0.0.1:8098/landing.html');
    await page.setViewportSize({width:390,height:844});
    await page.screenshot({path:path.join(output,'landing-mobile.png'),fullPage:true});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
    await page.getByRole('link',{name:'Buka demo penyelaras',exact:true}).click();
    await page.getByRole('heading',{name:'Gambaran keseluruhan',exact:true}).waitFor();
    pass('Landing desktop/mobile, module entry, portal return and demo CTA');
    await page.getByRole('link',{name:'Kembali ke portal',exact:true}).waitFor();
    await page.goto('http://127.0.0.1:8098/#actions');
    await page.getByRole('button',{name:'Lengkapkan bukti ujian pemulihan sandaran',exact:true}).click();
    await page.getByRole('button',{name:'Simulasi hantar untuk pengesahan',exact:true}).scrollIntoViewIfNeeded();
    const actionDialog=await page.getByRole('dialog').boundingBox();
    const actionButton=await page.getByRole('button',{name:'Simulasi hantar untuk pengesahan',exact:true}).boundingBox();
    assert.ok(actionButton.x>=actionDialog.x && actionButton.x+actionButton.width<=actionDialog.x+actionDialog.width);
    await page.screenshot({path:path.join(output,'action-mobile.png'),fullPage:true});
    await page.keyboard.press('Escape');
    await page.setViewportSize({width:1280,height:900});
    await page.goto('http://127.0.0.1:8098/#overview');
    await page.evaluate(()=>{document.activeElement.blur();window.scrollTo(0,0);});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
    await page.screenshot({path:path.join(output,'laptop.png'),fullPage:true});
    await page.goto('http://127.0.0.1:8098/#reports');
    await page.screenshot({path:path.join(output,'reports-desktop.png'),fullPage:true});
    pass('Mobile portal return, action footer and 1280px laptop fit');
    assert.deepEqual(errors,[]);
    pass('No browser JavaScript errors');
    fs.writeFileSync(path.join(output,'checks.json'),JSON.stringify({status:'passed',checks,errors,scope:'Synthetic mockup only; no backend/auth/security certification'},null,2));
  } finally { await browser.close(); }
})().catch(error=>{console.error(error);process.exitCode=1;});
